### ISSUE TITLE
Why you not using Laravel Fortify?

### ISSUE THREAD

**Issue by projct1** [manchenkoff/breeze-api#2]
Instead of ready-made routes, write your own?

**Comment by manchenkoff** [comment]
Hey @projct1, this project is a template created by Breeze starter kit. The endpoints are written by the Laravel team. 

Here I just added a bit more examples and kept it as a starting point for whose who need customization in the logic, but it is optional.

If you want to work with Fortify, you can easily do that.

**Comment by projct1** [comment]
Hey) Ok, thanks =)
